networks:
  wordpress:
    driver: bridge

services:
  db:
    image: mysql:9
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6-php8.4-fpm
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:9000:9000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://somervilleyimby.org');
        define('WP_SITEURL', 'https://somervilleyimby.org');
    volumes:
      - /var/www/html:/var/www/html
      - /var/www/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress

volumes:
  db:
